
# ================= US MARKET DATA =================
us_sectors = {
    "Technology": {
        "Consumer Electronics": ["Apple Inc.", "Garmin Ltd."],
        "Software": ["Microsoft Corp.", "Adobe Inc.", "Oracle Corp.", "Salesforce Inc."],
        "Semiconductors": ["NVIDIA Corp.", "Intel Corp.", "Advanced Micro Devices (AMD)", "Qualcomm Inc."]
    },
    "Communication Services": {
        "Interactive Media": ["Alphabet Inc. (Google)", "Meta Platforms (Facebook)", "Snap Inc."],
        "Entertainment": ["Netflix Inc.", "Walt Disney Co.", "Warner Bros. Discovery"]
    },
    "Consumer Discretionary": {
        "Automobile": ["Tesla Inc.", "Ford Motor Co.", "General Motors", "Rivian Automotive"],
        "E-commerce": ["Amazon.com Inc.", "eBay Inc.", "Etsy Inc."]
    },
    "Financials": {
        "Banks": ["JPMorgan Chase", "Bank of America", "Wells Fargo", "Citigroup Inc."],
        "Payments": ["Visa Inc.", "Mastercard Inc.", "PayPal Holdings"]
    },
    "Healthcare": {
        "Pharmaceuticals": ["Johnson & Johnson", "Pfizer Inc.", "Eli Lilly and Co."],
        "Biotechnology": ["Moderna Inc.", "Gilead Sciences", "Amgen Inc."]
    }
}

us_symbols = {
    # Technology
    "Apple Inc.": "AAPL", "Garmin Ltd.": "GRMN",
    "Microsoft Corp.": "MSFT", "Adobe Inc.": "ADBE", "Oracle Corp.": "ORCL", "Salesforce Inc.": "CRM",
    "NVIDIA Corp.": "NVDA", "Intel Corp.": "INTC", "Advanced Micro Devices (AMD)": "AMD", "Qualcomm Inc.": "QCOM",
    
    # Communication
    "Alphabet Inc. (Google)": "GOOGL", "Meta Platforms (Facebook)": "META", "Snap Inc.": "SNAP",
    "Netflix Inc.": "NFLX", "Walt Disney Co.": "DIS", "Warner Bros. Discovery": "WBD",
    
    # Consumer
    "Tesla Inc.": "TSLA", "Ford Motor Co.": "F", "General Motors": "GM", "Rivian Automotive": "RIVN",
    "Amazon.com Inc.": "AMZN", "eBay Inc.": "EBAY", "Etsy Inc.": "ETSY",
    
    # Financials
    "JPMorgan Chase": "JPM", "Bank of America": "BAC", "Wells Fargo": "WFC", "Citigroup Inc.": "C",
    "Visa Inc.": "V", "Mastercard Inc.": "MA", "PayPal Holdings": "PYPL",
    
    # Healthcare
    "Johnson & Johnson": "JNJ", "Pfizer Inc.": "PFE", "Eli Lilly and Co.": "LLY",
    "Moderna Inc.": "MRNA", "Gilead Sciences": "GILD", "Amgen Inc.": "AMGN"
}
sectors = {
    "Financial": {
        "Banks": [
            "JORDAN ISLAMIC BANK", "JORDAN KUWAIT BANK", "JORDAN COMMERCIAL BANK",
            "THE HOUSING BANK FOR TRADE AND FINANCE", "ARAB JORDAN INVESTMENT BANK",
            "SAFWA ISLAMIC BANK", "BANK AL ETIHAD", "ARAB BANKING CORPORATION /(JORDAN)",
            "INVEST BANK", "CAPITAL BANK OF JORDAN", "CAIRO AMMAN BANK",
            "BANK OF JORDAN", "JORDAN AHLI BANK", "ARAB BANK"
        ],
        "Insurance": [
            "MIDDLE EAST INSURANCE", "AL-NISR AL-ARABI INSURANCE", "JORDAN INSURANCE",
            "ARABIA INSURANCE COMPANY - JORDAN", "DELTA INSURANCE", "JERUSALEM INSURANCE",
            "THE UNITED INSURANCE", "JORDAN FRENCH INSURANCE", "AL MANARA ISLAMIC INSURANCE COMPANY",
            "GULF INSURANCE GROUP - JORDAN", "NATIONAL INSURANCE", "JORDAN INTERNATIONAL INSURANCE",
            "EURO ARAB INSURANCE GROUP", "THE ISLAMIC INSURANCE", "ARAB JORDANIAN INSURANCE GROUP",
            "THE MEDITERRANEAN & GULF INSURANCE COMPANY-JORDAN P.L.C", "FIRST INSURANCE"
        ],
        "Diversified Financial Services": [
            "NATIONAL PORTFOLIO SECURITIES", "JORDANIAN EXPATRIATES INVESTMENT HOLDING",
            "JORDAN INVESTMENT TRUST", "AL TAS-HEELAT JORDAN SPECIALIZED FINANCING",
            "ALDAMAN FOR INVESTMENTS", "UNION INVESTMENT CORPORATION", "JORDAN LOAN GUARANTEE CORPORATION",
            "ARAB EAST INVESTMENT", "UNITED FINANCIAL INVESTMENTS", "CENTURY INVESTMENT GROUP",
            "JORDAN MORTGAGE REFINANCE", "BINDAR FOR ISLAMIC FINANCE COMPANY", "AL-AMAL FINANCIAL INVESTMENTS CO.",
            "SHARECO BROKERAGE COMPANY", "AL SANABEL INTERNATIONAL FOR ISLAMIC INVESTMENTS(HOLDING) PLC. CO.",
            "AL-BILAD SECURITIES AND INVESTMENT", "FIRST FINANCE", "FUTURE ARAB INVESTMENT COMPANY",
            "BABELON INVESTMENTS CO. P.L.C", "KAFA`A FOR FINANCIAL & ECONOMICAL INVESTMENTS (P.L.C)",
            "TUHAMA FOR FINANCIAL INVESTMENTS", "FIRST JORDAN INVESTMENT COMPANY PLC",
            "DIMENSIONS:JORDAN AND EMIRATES COMMERCIAL INVESTMENTS CORPORATION", "DARAT JORDAN HOLDINGS",
            "SABAEK INVEST COMPANY P.L.C", "DAR AL AMAN FOR ISLAMIC FINANCE", "RUMM FINANCIAL BROKERAGE",
            "MIDDLE EAST HOLDING", "AKARY FOR INDUSTRIES AND REAL ESTATE INVESTMENTS",
            "Jordanian CO. For Developing & Financial Investment", "JORDANIAN MUTUAL FUNDS MANAGEMENT COMPANY"
        ],
        "Real Estate": [
            "ALSHAMEKHA FOR REALESTATE AND FINANCIAL INVESTMENTS", "JORDAN DECAPOLIS PROPERTIES",
            "AL-TAJAMOUAT FOR TOURISTIC PROJECTS CO PLC", "AL-TAJAMOUAT FOR CATERING AND HOUSING CO PLC",
            "SPECIALIZED INVESTMENT COMPOUNDS", "SPECIALIZED JORDANIAN INVESTMENT", "REAL ESTATE DEVELOPMENT",
            "THE REAL ESTATE & INVESTMENT PORTFOLIO CO.", "INT'L ARABIAN DEVELOPMENT AND INVESTMENT TRADING CO.",
            "JORDANIAN REALESTATE COMPANY FOR DEVELOPMENT", "AMAD INVESTMENT & REAL ESTATE DEVELOPMENT",
            "IHDATHIAT CO-ORDINATES", "ARAB PHOENIX HOLDINGS", "METHAQ REAL ESTATE INVESTMENT",
            "CONTEMPRO FOR HOUSING PROJECTS", "NOOR CAPITAL MARKTS FOR DIVERSIFIED INVESTMENTS",
            "HIGH PERFORMANCE REAL ESTATE INVESTMENTS", "ARAB INVESTORS UNION CO. FOR REAL ESTATES DEVELOPING",
            "JORDAN INTERNATIONAL INVESTMENT CO.", "DEERA INVESTMENT & REAL ESTATE DEVELOPMENT CO",
            "AL-TAHDITH FOR REAL ESTATE INVESTMENTS COMPANY", "THE PROFESSIONAL COMPANY FOR REAL ESTATE INVESTMENT AND HOUSING",
            "SHIRA REAL ESTATE DEVELOPMENT & INVESTMENTS", "AMWAJ PROPERTIES",
            "JORDAN MASAKEN FOR LAND & INDUSTRIAL DEVELOPMENT PROJECTS", "AMOUN INTERNATIONAL FOR INVESTMENTS",
            "ALENTKAEYA FOR INVESTMENT&REALESTATE DEVELOPMENT COMPANY PLC", "ARAB COMPANY FOR INVESTMENT PROJECTS",
            "LATENT ENERGIES FOR INVESTMENTS", "COMPREHENSIVE LAND DEVELOPMENT AND INVESTMENT",
            "AD-DULAYL INDUSTRIAL PARK & REAL ESTATE COMPANY P.L.C"
        ]
    },
    "Services": {
        "Health Care Services": [
            "THE CONSULTANT & INVESTMENT GROUP", "IBN ALHAYTHAM HOSPITAL COMPANY"
        ],
        "Educational Services": [
            "AL-ZARQA EDUCATIONAL & INVESTMENT", "THE ARAB INTERNATIONL FOR EDUCATION & INVESTMENT.",
            "AL-ISRA FOR EDUCATION AND INVESTMENT \"PLC\"", "PETRA EDUCATION COMPANY",
            "PHILADELPHIA INTERNATIONAL EDUCATIONAL INVESTMENT COMPANY"
        ],
        "Hotels and Tourism": [
            "JORDAN HOTELS & TOURISM", "ARAB INTERNATIONAL HOTELS", "MEDITERRANEAN TOURISM INVESTMENT",
            "ZARA INVESTEMENT HOLDING", "AL- SHARQ INVESTMENTS PROJECTS(HOLDING)", "AL-DAWLIYAH FOR HOTELS & MALLS",
            "AL-RAKAEZ INVESTMENT CO.", "SURA DEVELOPMENT & INVESTMENT PLC"
        ],
        "Transportation": [
            "JORDAN NATIONAL SHIPPING LINES", "SALAM INTERNATIONL TRANSPORT & TRADING",
            "JORDAN EXPRESS TOURIST TRANSPORT", "JORDAN INVESTMENT & TRANSPORT CO.",
            "TRANSPORT& INVESTMENT BARTER COMPANY", "MASAFAT FOR SPECIALISED TRANSPORT",
            "COMPREHENSIVE MULTIPLE TRANSPORTATIONS CO.", "UBOUR LOGISTIC SERVICES PLC"
        ],
        "Technology and Communication": [
            "JORDAN TELECOM", "AL-FARIS NATIONAL COMPANY FOR INVESTMENT & EXPORT"
        ],
        "Utilities and Energy": [
            "JORDAN ELECTRIC POWER", "IRBID DISTRICT ELECTRICITY", "AFAQ FOR ENERGY CO. P.L.C",
            "NATIONAL PETROULEUM", "SHEBA RENEWABLE ENERGY", "JORDAN PETROLEUM REFINERY"
        ],
        "Commercial Services": [
            "JORDANIAN DUTY FREE SHOPS", "JORDAN INTERNATIONAL TRADING CENTER", "SPECIALIZED TRADING & INVESTMENT",
            "OFFTEC HOLDING GROUP PLC", "NOBAR TRADING INVESTMENT COMPANY", "JORDANIAN MANAGEMENT AND CONSULTING COMPANY",
            "COMPREHENSIVE LEASING COMPANY PLC", "INJAZ FOR DEVELOPMENT & PROJECTS"
        ]
    },
    "Industrial": {
        "Pharmaceutical and Medical Industries": [
            "DAR AL DAWA DEVELOPMENT & INVESTMENT", "HAYAT PHARMACEUTICAL INDUSTRIES CO.",
            "PHILADELPHIA PHARMACEEUTICALS"
        ],
        "Chemical Industries": [
            "THE INDUSTRIAL COMMERCIAL & AGRICULTURAL", "PREMIER BUSINESS AND PROJECTS CO.LTD",
            "JORDAN INDUSTRIAL RESOURCES", "THE ARAB PESTICIDES & VETERINARY DRUGS MFG. CO."
        ],
        "Food and Beverages": [
            "JORDAN POULTRY PROCESSING & MARKETING", "JORDAN DAIRY", "GENERAL INVESTMENT",
            "UNIVERSAL MODERN INDUSTRIES", "NUTRI DAR", "JORDAN VEGETABLE OIL INDUSTRIES",
            "SINIORA FOOD INDUSTRIES PLC"
        ],
        "Tobacco and Cigarettes": ["UNION TOBACCO & CIGARETTE INDUSTRIES"],
        "Mining and Extraction Industries": [
            "ARAB ALUMINIUM INDUSTRY /ARAL", "NATIONAL STEEL INDUSTRY", "JORDAN PHOSPHATE MINES",
            "THE ARAB POTASH", "JORDAN STEEL", "NATIONAL ALUMINIUM INDUSTRIAL", "NORTHERN CEMENT CO."
        ],
        "Engineering and Construction": [
            "AFAQ HOLDING FOR INVESTMENT & REAL ESTATE DEVELOPMENT CO. P.L.C",
            "THE JORDAN PIPES MANUFACTURING", "READY MIX CONCRETE AND CONSTRUCTION SUPPLIES",
            "ARABIAN STEEL PIPES MANUFACTURING", "AL-QUDS READY MIX", "ASSAS FOR CONCRETE PRODUCTS CO. LTD"
        ],
        "Electrical Industries": ["UNITED CABLE INDUSTRIES"],
        "Textiles Leathers and Clothings": ["THE JORDAN WORSTED MILLS"]
    }
}
company_symbols = {
    # Financial - Banks
    "JORDAN ISLAMIC BANK": "JOIB",
    "JORDAN KUWAIT BANK": "JOKB",
    "JORDAN COMMERCIAL BANK": "JCBK",
    "THE HOUSING BANK FOR TRADE AND FINANCE": "THBK",
    "ARAB JORDAN INVESTMENT BANK": "AJIB",
    "SAFWA ISLAMIC BANK": "SIBK",
    "BANK AL ETIHAD": "ETHD",
    "ARAB BANKING CORPORATION /(JORDAN)": "ABCO",
    "INVEST BANK": "INVB",
    "CAPITAL BANK OF JORDAN": "CAPL",
    "CAIRO AMMAN BANK": "CABK",
    "BANK OF JORDAN": "BOJX",
    "JORDAN AHLI BANK": "AHLI",
    "ARAB BANK": "ARBK",

    # Financial - Insurance
    "MIDDLE EAST INSURANCE": "MEIN",
    "AL-NISR AL-ARABI INSURANCE": "AAIN",
    "JORDAN INSURANCE": "JOIN",
    "ARABIA INSURANCE COMPANY - JORDAN": "AICJ",
    "DELTA INSURANCE": "DICL",
    "JERUSALEM INSURANCE": "JERY",
    "THE UNITED INSURANCE": "UNIN",
    "JORDAN FRENCH INSURANCE": "JOFR",
    "AL MANARA ISLAMIC INSURANCE COMPANY": "MIIC",
    "GULF INSURANCE GROUP - JORDAN": "GIGJ",
    "NATIONAL INSURANCE": "NAAI",
    "JORDAN INTERNATIONAL INSURANCE": "JIJC",
    "EURO ARAB INSURANCE GROUP": "AMMI",
    "THE ISLAMIC INSURANCE": "TIIC",
    "ARAB JORDANIAN INSURANCE GROUP": "ARGR",
    "THE MEDITERRANEAN & GULF INSURANCE COMPANY-JORDAN P.L.C": "MDGF",
    "FIRST INSURANCE": "FINS",

    # Financial - Diversified Financial Services
    "NATIONAL PORTFOLIO SECURITIES": "MHFZ",
    "JORDANIAN EXPATRIATES INVESTMENT HOLDING": "JEIH",
    "JORDAN INVESTMENT TRUST": "JOIT",
    "AL TAS-HEELAT JORDAN SPECIALIZED FINANCING": "TJSF",
    "ALDAMAN FOR INVESTMENTS": "DMAN",
    "UNION INVESTMENT CORPORATION": "UINV",
    "JORDAN LOAN GUARANTEE CORPORATION": "JLGC",
    "ARAB EAST INVESTMENT": "AEIV",
    "UNITED FINANCIAL INVESTMENTS": "UCFI",
    "CENTURY INVESTMENT GROUP": "CEIG",
    "JORDAN MORTGAGE REFINANCE": "JMRC",
    "BINDAR FOR ISLAMIC FINANCE COMPANY": "BIND",
    "AL-AMAL FINANCIAL INVESTMENTS CO.": "AMAL",
    "SHARECO BROKERAGE COMPANY": "SHBC",
    "AL SANABEL INTERNATIONAL FOR ISLAMIC INVESTMENTS(HOLDING) PLC. CO.": "SANA",
    "AL-BILAD SECURITIES AND INVESTMENT": "BLAD",
    "FIRST FINANCE": "FFCO",
    "FUTURE ARAB INVESTMENT COMPANY": "FUTR",
    "BABELON INVESTMENTS CO. P.L.C": "SALM",
    "KAFA`A FOR FINANCIAL & ECONOMICAL INVESTMENTS (P.L.C)": "KAFA",
    "TUHAMA FOR FINANCIAL INVESTMENTS": "THMA",
    "FIRST JORDAN INVESTMENT COMPANY PLC": "FRST",
    "DIMENSIONS:JORDAN AND EMIRATES COMMERCIAL INVESTMENTS CORPORATION": "JEDI",
    "DARAT JORDAN HOLDINGS": "DARA",
    "SABAEK INVEST COMPANY P.L.C": "SABK",
    "DAR AL AMAN FOR ISLAMIC FINANCE": "DAIF",
    "RUMM FINANCIAL BROKERAGE": "RUMI",
    "MIDDLE EAST HOLDING": "MEHC",
    "AKARY FOR INDUSTRIES AND REAL ESTATE INVESTMENTS": "WOOL",
    "Jordanian CO. For Developing & Financial Investment": "JDFI",
    "JORDANIAN MUTUAL FUNDS MANAGEMENT COMPANY": "FUND",

    # Financial - Real Estate
    "ALSHAMEKHA FOR REALESTATE AND FINANCIAL INVESTMENTS": "VFED",
    "JORDAN DECAPOLIS PROPERTIES": "JDPC",
    "AL-TAJAMOUAT FOR TOURISTIC PROJECTS CO PLC": "TAJM",
    "AL-TAJAMOUAT FOR CATERING AND HOUSING CO PLC": "JNTH",
    "SPECIALIZED INVESTMENT COMPOUNDS": "SPIC",
    "SPECIALIZED JORDANIAN INVESTMENT": "SIJC",
    "REAL ESTATE DEVELOPMENT": "REDV",
    "THE REAL ESTATE & INVESTMENT PORTFOLIO CO.": "AQAR",
    "INT'L ARABIAN DEVELOPMENT AND INVESTMENT TRADING CO.": "INMA",
    "JORDANIAN REALESTATE COMPANY FOR DEVELOPMENT": "JRCD",
    "AMAD INVESTMENT & REAL ESTATE DEVELOPMENT": "AMAD",
    "IHDATHIAT CO-ORDINATES": "IHCO",
    "ARAB PHOENIX HOLDINGS": "PHNX",
    "METHAQ REAL ESTATE INVESTMENT": "MEET",
    "CONTEMPRO FOR HOUSING PROJECTS": "COHO",
    "NOOR CAPITAL MARKTS FOR DIVERSIFIED INVESTMENTS": "NCMD",
    "HIGH PERFORMANCE REAL ESTATE INVESTMENTS": "HIPR",
    "ARAB INVESTORS UNION CO. FOR REAL ESTATES DEVELOPING": "UNAI",
    "JORDAN INTERNATIONAL INVESTMENT CO.": "JIIG",
    "DEERA INVESTMENT & REAL ESTATE DEVELOPMENT CO": "DERA",
    "AL-TAHDITH FOR REAL ESTATE INVESTMENTS COMPANY": "THDI",
    "THE PROFESSIONAL COMPANY FOR REAL ESTATE INVESTMENT AND HOUSING": "PROF",
    "SHIRA REAL ESTATE DEVELOPMENT & INVESTMENTS": "SHRA",
    "AMWAJ PROPERTIES": "AMWJ",
    "JORDAN MASAKEN FOR LAND & INDUSTRIAL DEVELOPMENT PROJECTS": "MSKN",
    "AMOUN INTERNATIONAL FOR INVESTMENTS": "AMON",
    "ALENTKAEYA FOR INVESTMENT&REALESTATE DEVELOPMENT COMPANY PLC": "ENTK",
    "ARAB COMPANY FOR INVESTMENT PROJECTS": "APCT",
    "LATENT ENERGIES FOR INVESTMENTS": "LEIN",
    "COMPREHENSIVE LAND DEVELOPMENT AND INVESTMENT": "CLDI",
    "AD-DULAYL INDUSTRIAL PARK & REAL ESTATE COMPANY P.L.C": "IDMC",

    # Services - Health Care
    "THE CONSULTANT & INVESTMENT GROUP": "CICO",
    "IBN ALHAYTHAM HOSPITAL COMPANY": "IBNH",

    # Services - Educational
    "AL-ZARQA EDUCATIONAL & INVESTMENT": "ZEIC",
    "THE ARAB INTERNATIONL FOR EDUCATION & INVESTMENT.": "AIEI",
    "AL-ISRA FOR EDUCATION AND INVESTMENT \"PLC\"": "AIFE",
    "PETRA EDUCATION COMPANY": "PEDC",
    "PHILADELPHIA INTERNATIONAL EDUCATIONAL INVESTMENT COMPANY": "PIEC",

    # Services - Hotels and Tourism
    "JORDAN HOTELS & TOURISM": "JOHT",
    "ARAB INTERNATIONAL HOTELS": "AIHO",
    "MEDITERRANEAN TOURISM INVESTMENT": "MDTR",
    "ZARA INVESTEMENT HOLDING": "ZARA",
    "AL- SHARQ INVESTMENTS PROJECTS(HOLDING)": "AIPC",
    "AL-DAWLIYAH FOR HOTELS & MALLS": "MALL",
    "AL-RAKAEZ INVESTMENT CO.": "RICS",
    "SURA DEVELOPMENT & INVESTMENT PLC": "SURA",

    # Services - Transportation
    "JORDAN NATIONAL SHIPPING LINES": "SHIP",
    "SALAM INTERNATIONL TRANSPORT & TRADING": "SITT",
    "JORDAN EXPRESS TOURIST TRANSPORT": "JETT",
    "JORDAN INVESTMENT & TRANSPORT CO.": "ALFA",
    "TRANSPORT& INVESTMENT BARTER COMPANY": "NAQL",
    "MASAFAT FOR SPECIALISED TRANSPORT": "MSFT",
    "COMPREHENSIVE MULTIPLE TRANSPORTATIONS CO.": "ABUS",
    "UBOUR LOGISTIC SERVICES PLC": "TRUK",

    # Services - Technology and Communication
    "JORDAN TELECOM": "JTEL",
    "AL-FARIS NATIONAL COMPANY FOR INVESTMENT & EXPORT": "CEBC",

    # Services - Utilities and Energy
    "JORDAN ELECTRIC POWER": "JOEP",
    "IRBID DISTRICT ELECTRICITY": "IREL",
    "AFAQ FOR ENERGY CO. P.L.C": "MANE",
    "NATIONAL PETROULEUM": "NAPT",
    "SHEBA RENEWABLE ENERGY": "SHBA",
    "JORDAN PETROLEUM REFINERY": "JOPT",

    # Services - Commercial
    "JORDANIAN DUTY FREE SHOPS": "JDFS",
    "JORDAN INTERNATIONAL TRADING CENTER": "JITC",
    "SPECIALIZED TRADING & INVESTMENT": "SPTI",
    "OFFTEC HOLDING GROUP PLC": "OFTC",
    "NOBAR TRADING INVESTMENT COMPANY": "NOTI",
    "JORDANIAN MANAGEMENT AND CONSULTING COMPANY": "JOMC",
    "COMPREHENSIVE LEASING COMPANY PLC": "LEAS",
    "INJAZ FOR DEVELOPMENT & PROJECTS": "ATCO",

    # Industrial - Pharmaceutical
    "DAR AL DAWA DEVELOPMENT & INVESTMENT": "DADI",
    "HAYAT PHARMACEUTICAL INDUSTRIES CO.": "HPIC",
    "PHILADELPHIA PHARMACEEUTICALS": "PHIL",

    # Industrial - Chemical
    "THE INDUSTRIAL COMMERCIAL & AGRICULTURAL": "ICAG",
    "PREMIER BUSINESS AND PROJECTS CO.LTD": "ACDT",
    "JORDAN INDUSTRIAL RESOURCES": "JOIR",
    "THE ARAB PESTICIDES & VETERINARY DRUGS MFG. CO.": "MBED",

    # Industrial - Food & Beverages
    "JORDAN POULTRY PROCESSING & MARKETING": "JPPC",
    "JORDAN DAIRY": "JODA",
    "GENERAL INVESTMENT": "GENI",
    "UNIVERSAL MODERN INDUSTRIES": "UMIC",
    "NUTRI DAR": "NDAR",
    "JORDAN VEGETABLE OIL INDUSTRIES": "JVOI",
    "SINIORA FOOD INDUSTRIES PLC": "SNRA",

    # Industrial - Tobacco
    "UNION TOBACCO & CIGARETTE INDUSTRIES": "UTOB",

    # Industrial - Mining and Extraction
    "ARAB ALUMINIUM INDUSTRY /ARAL": "AALU",
    "NATIONAL STEEL INDUSTRY": "NAST",
    "JORDAN PHOSPHATE MINES": "JOPH",
    "THE ARAB POTASH": "APOT",
    "JORDAN STEEL": "JOST",
    "NATIONAL ALUMINIUM INDUSTRIAL": "NATA",
    "NORTHERN CEMENT CO.": "NCCO",

    # Industrial - Engineering and Construction
    "AFAQ HOLDING FOR INVESTMENT & REAL ESTATE DEVELOPMENT CO. P.L.C": "MANR",
    "THE JORDAN PIPES MANUFACTURING": "JOPI",
    "READY MIX CONCRETE AND CONSTRUCTION SUPPLIES": "RMCC",
    "ARABIAN STEEL PIPES MANUFACTURING": "ASPMM",
    "AL-QUDS READY MIX": "AQRM",
    "ASSAS FOR CONCRETE PRODUCTS CO. LTD": "ASAS",

    # Industrial - Electrical
    "UNITED CABLE INDUSTRIES": "UCIC",

    # Industrial - Textiles
    "THE JORDAN WORSTED MILLS": "JOWM"
}
company_export_ids = {
    "JOIB": 193,
    "JOKB": 195,
    "JCBK": 197,
    "THBK": 199,
    "AJIB": 201,
    "SIBK": 203,
    "ETHD": 205,
    "ABCO": 207,
    "INVB": 211,
    "CAPL": 213,
    "CABK": 217,
    "BOJX": 219,
    "AHLI": 223,
    "ARBK": 227,

    # Insurance
    "MEIN": 231,
    "AAIN": 233,
    "JOIN": 235,
    "AICJ": 237,
    "DICL": 239,
    "JERY": 241,
    "UNIN": 243,
    "JOFR": 245,
    "MIIC": 253,
    "GIGJ": 255,
    "NAAI": 267,
    "JIJC": 269,
    "AMMI": 271,
    "TIIC": 275,
    "ARGR": 279,
    "MDGF": 283,
    "FINS": 287,
    "JOIB": 193,
    "JOKB": 195,
    "JCBK": 197,
    "THBK": 199,
    "AJIB": 201,
    "SIBK": 203,
    "ETHD": 205,
    "ABCO": 207,
    "INVB": 211,
    "CAPL": 213,
    "CABK": 217,
    "BOJX": 219,
    "AHLI": 223,
    "ARBK": 227,

    # Insurance
    "MEIN": 231,
    "AAIN": 233,
    "JOIN": 235,
    "AICJ": 237,
    "DICL": 239,
    "JERY": 241,
    "UNIN": 243,
    "JOFR": 245,
    "MIIC": 253,
    "GIGJ": 255,
    "NAAI": 267,
    "JIJC": 269,
    "AMMI": 271,
    "TIIC": 275,
    "ARGR": 279,
    "MDGF": 283,
    "FINS": 287,

    # Diversified Financial Services
    "MHFZ": 311,
    "JEIH": 319,
    "JOIT": 335,
    "TJSF": 349,
    "DMAN": 353,
    "UINV": 359,
    "JLGC": 363,
    "AEIV": 383,
    "UCFI": 397,
    "CEIG": 405,
    "JMRC": 413,
    "BIND": 449,
    "AMAL": 473,
    "SHBC": 507,
    "SANA": 509,
    "BLAD": 511,
    "FFCO": 513,
    "FUTR": 527,
    "SALM": 531,
    "KAFA": 545,
    "THMA": 547,
    "FRST": 549,
    "JEDI": 553,
    "DARA": 559,
    "SABK": 561,
    
    "DAIF": 573,
    "RUMI": 587,
    "MEHC": 4413,
    "WOOL": 643,
    "JDFI": 645,
    "TAJM": 313,
    "JDPC": 309,
    "VFED": 299,
    "FUND": 805,
    "JNTH": 371,
    "SPIC": 373,
    "SIJC": 389,
    "REDV": 391,
    "AQAR": 409,
    "INMA": 461,
    "JRCD": 469,
    "AMAD": 479,
    "IHCO": 483,
    "PHNX": 489,
    "MEET": 491,
    "COHO": 493,
    "NCMD": 501,
    "HIPR": 503,
    "UNAI": 505,
    "JIIG": 517,
    "DERA": 521,
    "THDI": 541,
    "PROF": 551,
    "SHRA": 565,
    "AMWJ": 571,
    "MSKN": 577,
    "AMON": 579,
    "ENTK": 583,
    "LEIN": 615,
    "ATTA": 649,
    "IDMC": 749,
    "CICO": 427,
    "IBNH": 567,
    "ZEIC": 341,
    "AIEI": 343,
    "AIFE": 451,
    "PIEC": 455,
    "JOHT": 291,
    "AIHO": 295,
    "MDTR": 331,
    "ZARA": 357,
    "AIPC": 375,
    "MALL": 407,
    "RICS": 533,
    "SURA": 575,
    "SHIP": 301,
    "SITT": 329,
    "JETT": 379,
    "ALFA": 385,
    "NAQL": 429,
    "MSFT": 497,
    "TRUK": 589,
    "JTEL": 425,
    "CEBC": 475,
    "IREL": 297,
    "MANE": 581,
    "SHBA": 815,
    "JOPT": 819,
    "JITC": 317,
    "SPTI": 381,
    "OFTC": 467,
    "NOTI": 487,
    "JOMC": 515,
    "LEAS": 539,
    "ATCO": 679,
    "DADI": 609,
    "HPIC": 789,
    "PHIL": 807,
    "ICAG": 603,
    "ACDT": 605,
    "JOIR": 675,
    "MBED": 787,
    "JPPC": 591,
    "JODA": 595,
    "GENI": 639,
    "UMIC": 669,
    "NDAR": 733,
    "JVOI": 767,
    "SNRA": 813,
    "UTOB": 705,
    "AALU": 599,
    "NAST": 607,
    "JOPH": 619,
    "APOT": 659,
    "JOST": 699,
    "NATA": 729,
    "NCCO": 817,
    "MANR": 529,
    "JOPI": 621,
    "RMCC": 691,
    "ASPMM": 739,
    "AQRM": 785,
    "ASAS": 797,
    "UCIC": 799,
    "JOWM": 613
}
